name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: py-${{ matrix.python-version }} k8senv
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: .
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test Dashboard
        working-directory: .
        run: |
          pytest
          flake8
